[manifest]
version = "0.1"
dump_lua = false
priority = 0

# Замена шрифта, TEXT_HEIGHT_SCALE - межстрочный интервал, self.TILESIZE - размер UI кнопок с текстом, 
# TEXT_OFFSET - смещение текста, FONTSCALE - размер шрифта, DESCSCALE - размер описаний карт
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''{file = "resources/fonts/NotoSans-Bold.ttf", render_scale = self.TILESIZE*7, TEXT_HEIGHT_SCALE = 0.65, TEXT_OFFSET = {x=0,y=-40}, FONTSCALE = 0.12, squish = 1, DESCSCALE = 1},'''
position = "at"
payload = '''{file = "resources/fonts/NotoSans-Bold.ttf", render_scale = self.TILESIZE*10, TEXT_HEIGHT_SCALE = 0.8, TEXT_OFFSET = {x=0,y=-40}, FONTSCALE = 0.1, squish = 1, DESCSCALE = 1},'''
overwrite = true
match_indent = true

# Локализация для строки "Not Allowed!"
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''play_area_status_text("Not Allowed!")--localize('k_not_allowed_ex'), true)'''
position = "at"
payload = '''play_area_status_text(localize('k_not_allowed_ex'))'''
overwrite = true
match_indent = true

# Исправление центрирования кнопки "Сыграть руку"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local play_button = {n=G.UIT.C, config={id = 'play_button', align = "tm", minw = 2.5, padding = 0.3, r = 0.1, hover = true, colour = G.C.BLUE, button = "play_cards_from_highlighted", one_press = true, shadow = true, func = 'can_play'}, nodes={'''
position = "at"
payload = '''local play_button = {n=G.UIT.C, config={id = 'play_button', align = "cm", minw = 2.5, padding = 0.3, r = 0.1, hover = true, colour = G.C.BLUE, button = "play_cards_from_highlighted", one_press = true, shadow = true, func = 'can_play'}, nodes={'''
overwrite = true
match_indent = true

# Исправление центрирования кнопки "Сбросить"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local discard_button = {n=G.UIT.C, config={id = 'discard_button',align = "tm", padding = 0.3, r = 0.1, minw = 2.5, minh = button_height, hover = true, colour = G.C.RED, button = "discard_cards_from_highlighted", one_press = true, shadow = true, func = 'can_discard'}, nodes={'''
position = "at"
payload = '''local discard_button = {n=G.UIT.C, config={id = 'discard_button',align = "cm", padding = 0.3, r = 0.1, minw = 2.5, minh = button_height, hover = true, colour = G.C.RED, button = "discard_cards_from_highlighted", one_press = true, shadow = true, func = 'can_discard'}, nodes={'''
overwrite = true
match_indent = true

# Исправление центрирования кнопки "Пропустить"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R,config={align = "tm",padding = 0.2, minh = 1.2, minw = 1.8, r=0.15,colour = G.C.GREY, one_press = true, button = 'skip_booster', hover = true,shadow = true, func = 'can_skip_booster'}, nodes = {'''
position = "at"
payload = '''{n=G.UIT.R,config={align = "cm",padding = 0.2, minh = 1.2, minw = 1.8, r=0.15,colour = G.C.GREY, one_press = true, button = 'skip_booster', hover = true,shadow = true, func = 'can_skip_booster'}, nodes = {'''
overwrite = true
match_indent = true

# Локализация для строки "Round score"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.T, config={text = localize('k_round'), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "Текущий", scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.T, config={text =localize('k_lower_score'), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "счёт", scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
overwrite = true
match_indent = true

# Исправление размера текста на кнопке "Next round"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R, config={align = "cm", maxw = 1.3}, nodes={'''
position = "at"
payload = '''{n=G.UIT.R, config={align = "cm", maxw = 2}, nodes={'''
overwrite = true
match_indent = true

# Локализация для строки "View deck"
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = localize('k_deck'), scale = 0.38, colour = G.C.WHITE, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "колоду", scale = 0.38, colour = G.C.WHITE, shadow = true}}'''
overwrite = true
match_indent = true

# Текущая версия локализации
[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "VERSION = VERSION..'-FULL'"
position = "after"
payload = "VERSION = VERSION..' (Локализация от Nitablade, v1.0.3)'"
overwrite = false
match_indent = true